-- BUS-ADM 749 Data and Information Management
-- Michael Noel
-- Continental Palms DVD
-- test_execute_procedures.sql

-- TESTING CHECKOUT()

-- FAIL. Member does not exist.
BEGIN DBMS_OUTPUT.PUT_LINE('TEST SHOULD FAIL. ORA-20001. Member does not exist.'); END;
BEGIN CHECKOUT( THECATALOGNO => 'D00001', THECOPYNO => 1, THEMEMBER => 12345); END;

-- FAIL. DVD does not exist.
BEGIN DBMS_OUTPUT.PUT_LINE('TEST SHOULD FAIL. ORA-20002. DVD does not exist.'); END;
BEGIN CHECKOUT(THECATALOGNO => 'D12345', THECOPYNO => 1, THEMEMBER => 10000); END;

-- FAIL. DVDCopy does not exist.
BEGIN DBMS_OUTPUT.PUT_LINE('TEST SHOULD FAIL. ORA-20003. DVDCopy does not exist.'); END;
BEGIN CHECKOUT( THECATALOGNO => 'D00001', THECOPYNO => 25, THEMEMBER => 10000); END;

-- FAIL. DVDCopy Condition is 4
BEGIN DBMS_OUTPUT.PUT_LINE('TEST SHOULD FAIL. ORA-20004. DVDCopy Broken.'); END;
BEGIN CHECKOUT(THECATALOGNO => 'D00007', THECOPYNO => 3, THEMEMBER => 10000); END;

-- SUCCESS. Conditions satisfied.
BEGIN CHECKOUT( THECATALOGNO => 'D00001', THECOPYNO => 2, THEMEMBER => 10000, THERENTALDATE=> '02-OCT-2020'); END;

-- FAIL. DVDCopy already checkout.
BEGIN DBMS_OUTPUT.PUT_LINE('TEST SHOULD FAIL. ORA-20005. DVDCopy already checked out.'); END;
BEGIN CHECKOUT( THECATALOGNO => 'D00001', THECOPYNO => 2, THEMEMBER => 10000); END;


-- TESTING CHECKIN()
